version: 1.0
configuration:
  spotify:        
    redirectUri: http://localhost:50555/callback
    refreshMarginInMinutes: 10
    startSpotifyClient: false
    latestTracksCount: 1000
    scopes:
      - user-read-playback-state
      - user-modify-playback-state
      - user-read-currently-playing
      - user-read-private
      - user-read-email
      - user-top-read
      - playlist-read-private
      - playlist-modify-public
      - playlist-modify-private    
  core:
    name: Spotify Prompt
    version: 1.0
    prompt: cp>
    defaultCommand: search
    showLogo: true
    logoColor: LightGreen
    suggestions: 
    - exit
    roamingDirectory: SpotifyPrompt
    modules:
      security:
        secrets:
        - name: spotify_prompt
          options:
            target: User
      storage:
        applicationDataFolder: $ROAMING$/SpotifyPrompt
        backupPath: backup      
      infoPanel:
        enabled: true
        height: 2
        updateIntervalSeconds: -1
      ollama:
        baseAddress: localhost
        port: 11434
        model: gemma3:27b
  log:
    fileName: commandprompt.log
    filePath: logs
    rollingIntervall: Day
    restrictedToMinimumLevel: Warning